media: media

content:
  - name: writing
    label: Writing
    type: collection
    path: content/writing
    format: yaml-frontmatter
    filename: "{primary}.md"
    fields:
      - name: title
        label: Title
        type: string
        required: true

      - name: description
        label: Description
        type: text

      - name: date
        label: Date
        type: date

      - name: body
        label: Body
        type: rich-text

  - name: library
    label: Library
    type: collection
    path: content/library
    format: yaml-frontmatter
    filename: "{primary}.md"
    fields:
      - name: title
        label: Title
        type: string
        required: true

      - name: author
        label: Author
        type: string

      - name: description
        label: Description
        type: text

      - name: date
        label: Date
        type: date

      - name: body
        label: Body
        type: rich-text

   - name: now
    label: Now
    type: file
    path: content/now.md
    format: yaml-frontmatter
    fields:
      - name: layout
        type: string
        hidden: true
        default: page.njk

      - name: bodyClass
        type: string
        hidden: true
        default: standard-page

      - name: activeSection
        type: string
        hidden: true
        default: now

      - name: permalink
        type: string
        hidden: true
        default: /now/

      - name: title
        label: Title
        type: string

      - name: updated
        label: Updated
        type: date

      - name: body
        label: Body
        type: rich-text

  - name: about
    label: About
    type: file
    path: content/about.md
    format: yaml-frontmatter
    fields:
      - name: layout
        type: string
        hidden: true
        default: page.njk

      - name: bodyClass
        type: string
        hidden: true
        default: standard-page

      - name: activeSection
        type: string
        hidden: true
        default: about

      - name: permalink
        type: string
        hidden: true
        default: /about/

      - name: title
        label: Title
        type: string

      - name: body
        label: Body
        type: rich-text

  - name: navigation
    label: Navigation
    type: file
    path: data/navigation.json
    format: code
